# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8081
    #打开注释，则通过【http://localhost/renren-fast】访问
    servlet: 
        context-path: /financial

spring:
    # 环境 dev|test|pro
    profiles:
        active: dev
    #热部署：页面修改及时生效
    thymeleaf:
        cache: false
     #热部署生效
    devtools:
        restart:
          enabled: false
     #设置重启的目录
     #additional-paths: src/main/java
     #classpath目录下的WEB-INF文件夹内容修改不重启
          #exclude: WEB-INF/**
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    resources: # 指定静态资源的路径
        static-locations: classpath:/static/,classpath:/views/
    redis:
        open: false  # 是否开启redis缓存  true开启   false关闭
        database: 0
        host: 127.0.0.1
        port: 16379
        password:       # 密码（默认为空）
        timeout: 6000  # 连接超时时长（毫秒）
        pool:
            max-idle: 10       # 连接池中的最小空闲连接
        jedis:
            pool:
                max-idle: 1000
                max-wait:
                min-idle: 5

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    configLocation: classpath:mybatis.xml

